# Generated by Django 3.0.3 on 2020-02-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin'))},
        ),
    ]
